### ISSUE TITLE
V2 RoadMap

### ISSUE THREAD

**Issue by gs-akhan** [gs-akhan/react-native-chooser#22]
Hi, These are the features being targeted for V2

- [x] Multiple Selection - Allowing users to multiselect options. Just like <select multiple >...</select>
- [x] <View /> as option  - Allowing to pass Views to options, this will allow users to have icons inside options
- [x] Slide the selection menu from Top or Bottom of screen ..
- [ ] Searching options.
@stoffern @technology-studio-apiary

Thanks

**Comment by st0ffern** [comment]
How about a dropdown instead of a modal overlay?

**Comment by gs-akhan** [comment]
Yeah Good question. But positioning is one hell of thing. 
I have contributed at lot to [https://github.com/alinz/react-native-dropdown](https://github.com/alinz/react-native-dropdown). 

But the problem is when we embed the component inside navigator or otherviews the top and left positions are relative to parent component. 
So what I thought is to have a complete view for selection. It is easy UX wise too and also coding wise. 

We can have that options too, if we collectively decide.

**Comment by rostislav-simonik** [comment]
@gs-akhan Have you had chance to validate my sample for setSelectedText #20 alternative through props ? Would you like me to create pull request for given approach?

**Comment by st0ffern** [comment]
@gs-akhan i will fix v2 by this week, just need to land a few things @ work

**Comment by gs-akhan** [comment]
Cool. Create a branch we both can share the features and implement them

**Comment by gs-akhan** [comment]
@rostislav-simonik  I havent. will do it tonight.

**Comment by rostislav-simonik** [comment]
@gs-akhan Ok, thanks, let me know then and  I'll do a more clean proposal.

**Comment by st0ffern** [comment]
@gs-akhan can you add me as collaborator on NPM?
Also activate Travis on the repo 😉

I am starting with v2 now

**Comment by gs-akhan** [comment]
Sure sir !!

**Comment by gs-akhan** [comment]
@stoffern  What's your NPM profile name ?

**Comment by st0ffern** [comment]
https://www.npmjs.com/~stoffern

**Comment by st0ffern** [comment]
added 
`direction (fromLeft, fromRight, fromTop, fromBottom)`
and 
`renderButton={ currentValue => <Text>{'Current Value: ' + currentValue}</Text> }`

more to come later on v2

**Comment by gs-akhan** [comment]
Did You get access ?

**Comment by gs-akhan** [comment]
Activated Travis

**Comment by st0ffern** [comment]
i feed we should remove sending styles into the Select and rather let the user send custom components into it with styles..

This is for `SelectButton` and `Options`

**Comment by st0ffern** [comment]
passing it like this:
```js
renderButton={ currentValue => <Text>{'Current Value: ' + currentValue}</Text> }
renderOptionItem = { ({value, text, index}) => <View key={index} style={{}}>{text}</View>}
renderOptionSeperator={ data => <View style={{height: 1, backgroundColor: 'black'}}></View>}
```

**Comment by gs-akhan** [comment]
How would end API look like.. ? Are we getting rid of <Option> </Option>
Component then, and then replacing it with renderOptionItem ?

**Comment by gs-akhan** [comment]
Ohh Got it. Lets accept styles. that should not be a worry.

**Comment by gs-akhan** [comment]
Passing Component would be little too much to do for users. I think so

**Comment by st0ffern** [comment]
It's a normal practise to do in React. Look at `ListView` and `FlatList`
I think if you dont pass in a custom component it will just render default layout..

So it is optional

**Comment by gs-akhan** [comment]
Let's go with it .. once it is all done we will see if we can make it even
simpler

**Comment by rostislav-simonik** [comment]
@gs-akhan @stoffern Hi guys, what about the change I have been proposing. The one which substitutes setSelectedText with props logic?

**Comment by st0ffern** [comment]
@rostislav-simonik i am rewriting the Select totally, into v2.
There will be no `setSelectText` 😉

**Comment by st0ffern** [comment]
@gs-akhan how do you want to solve the multiple select?
What should the user do after he has selected multiple items in order to confirm selections?

**Comment by gs-akhan** [comment]
@rostislav-simonik  Yeaah your concerns are taken care by @stoffern 's fix. 

@stoffern  
So the API for multiselect should be based of prop `multiple = true` just like we have in HTML Select tag.

And selected values should be as array of options selected.

**Comment by st0ffern** [comment]
Yes, but when is the user done selecting?

**Comment by gs-akhan** [comment]
yes. That should be ok.
You have any suggestions ?

**Comment by st0ffern** [comment]
Then er need a "done" button?

**Comment by gs-akhan** [comment]
No, we can close the menu my tapping anywhere outside. the will trigger
"close" dropdown

**Comment by stoffern** [comment]
Ok, that will be the last piece in the puzzle..

**Comment by st0ffern** [comment]
done

**Comment by st0ffern** [comment]
I think "Searching options" should be a v3.. 
Lets keep changes to a minimum in v2 and making it compatible for upgrades..

There are breaking changes in v2, but they are also taking future updates into conciderations so they will not be breaking later on.
cc @gs-akhan

**Comment by gs-akhan** [comment]
Perfect.  I am good with that..  Is every thing committed to v2 branch ?

**Comment by st0ffern** [comment]
yup, needs some testing..
I will fix Travis testings and README.md + MIGRATION.md later today

**Comment by gs-akhan** [comment]
I can test tonight from that branch ..

**Comment by rtman** [comment]
@gs-akhan I realize this is a few months old by now but do you still have plans to release v2?

**Comment by gs-akhan** [comment]
@rtman  Yes we would like you. The thing is we need some beta testers who can validate if its working well. If you wish to help it. we can make a release. 

Thanks

**Comment by rtman** [comment]
@gs-akhan 
Hey I'm willing to test it in my app, I can't guarantee I can help too much in any debug but I can report what is happening. My time is a bit limited at the moment since I am developing full time with a deadline looming.

**Comment by gs-akhan** [comment]
@rtman  Absolutely yes sir. :)

**Comment by st0ffern** [comment]
Back from a longer vacation 😉 what is the status of v2 ? 😄

**Comment by st0ffern** [comment]
Should i continue on this one?

**Comment by gs-akhan** [comment]
Yes.. with full force
